# Auto-generated by menu.py
symbols = ['AAVEUSDT', 'ACTUSDT', 'BNBUSDT', 'BTCUSDT', 'ETHUSDT', 'MANTAUSDT', 'NEARUSDT', 'SOLUSDT']
years = 2
types = {'spot': True, 'perp': True, 'funding': False, 'metrics': False}
upload = True
