"""Интерактивное меню загрузки данных Binance.

Использование:
    python -m data_fetcher menu
    python -m data_fetcher menu --run   (без интерактива, с сохранённым конфигом)
"""

import sys
import json
import time
from pathlib import Path
from datetime import datetime, timezone, timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests

from data_fetcher import config

CONFIG_PATH = Path("menu_config.py")
STABLECOINS = frozenset({"USDC", "FDUSD", "USDP", "TUSD", "DAI", "USDD",
                          "BUSD", "FRAX", "LUSD", "GHO"})

# ── Загрузка/сохранение конфига ──


def _load():
    if not CONFIG_PATH.exists():
        return {"symbols": ["BTCUSDT", "ETHUSDT"], "years": 1,
                "types": {"spot": True, "perp": True, "funding": False, "metrics": False},
                "upload": False}
    ns = {}
    exec(CONFIG_PATH.read_text(), ns)
    return {k: ns.get(k, v) for k, v in [
        ("symbols", ["BTCUSDT", "ETHUSDT"]), ("years", 1),
        ("types", {"spot": True, "perp": True, "funding": False, "metrics": False}),
        ("upload", False)]}


def _save(cfg):
    CONFIG_PATH.write_text(
        f"# Auto-generated by menu.py\n"
        f"symbols = {cfg['symbols']!r}\n"
        f"years = {cfg['years']!r}\n"
        f"types = {cfg['types']!r}\n"
        f"upload = {cfg['upload']!r}\n"
    )

# ── Получение пар с Binance ──


def _fetch_exchange_info(url):
    for _ in range(3):
        try:
            resp = requests.get(url, timeout=10)
            if resp.status_code == 200:
                return resp.json().get("symbols", [])
        except Exception:
            time.sleep(1)
    return []


def get_pairs():
    """Вернуть список dict-ов: {symbol, baseAsset, volume_usd}, топ по объёму."""
    spot_data = _fetch_exchange_info("https://api.binance.com/api/v3/exchangeInfo")
    spot = {s["symbol"]: s for s in spot_data
            if s.get("quoteAsset") == "USDT" and s.get("status") == "TRADING"}

    perp_data = _fetch_exchange_info("https://fapi.binance.com/fapi/v1/exchangeInfo")
    perp = {s["symbol"]: s for s in perp_data
            if s.get("quoteAsset") == "USDT" and s.get("contractType") == "PERPETUAL" and s.get("status") == "TRADING"}

    common = sorted(set(spot.keys()) & set(perp.keys()))
    common = [s for s in common if spot[s]["baseAsset"] not in STABLECOINS]

    # объёмы
    volumes = {}
    for i in range(0, len(common), 100):
        batch = common[i:i + 100]
        symbols_json = json.dumps(batch, separators=(",", ":"))
        for _ in range(3):
            try:
                resp = requests.get("https://api.binance.com/api/v3/ticker/24hr",
                                    params={"symbols": symbols_json}, timeout=15)
                if resp.status_code == 200:
                    for t in resp.json():
                        volumes[t["symbol"]] = float(t.get("quoteVolume", 0) or 0)
                    break
            except Exception:
                time.sleep(1)

    pairs = [{"symbol": s, "baseAsset": spot[s]["baseAsset"],
              "volume_usd": volumes.get(s, 0)} for s in common]
    return sorted(pairs, key=lambda x: x["volume_usd"], reverse=True)


def input_line(prompt, default=None):
    if default is not None:
        return input(f"{prompt} [{default}]: ").strip() or default
    return input(f"{prompt}: ").strip()


def show_menu(cfg):
    """Отобразить главное меню, вернуть выбранное действие."""
    now = datetime.now(timezone.utc)
    start = now - timedelta(days=365 * cfg["years"])

    print()
    print("  ╔═══════════════════════════════════════╗")
    print("  ║  Binance Data Downloader             ║")
    print("  ╚═══════════════════════════════════════╝")
    print()
    print("  Текущие настройки:")
    print(f"  ─{'─'*55}")
    print(f"    1. Период: {cfg['years']} год(а) ({start.date()} → {now.date()})")
    n = len(cfg["symbols"])
    sym_str = ", ".join(cfg["symbols"][:5])
    if n > 5:
        sym_str += f" ... (+{n-5})"
    print(f"    2. Символы: {sym_str} ({n})")
    active = [k for k, v in cfg["types"].items() if v]
    print(f"    3. Типы: {', '.join(active)}")
    print(f"    4. Upload в bucket: {'да' if cfg['upload'] else 'нет'}")
    print()
    print(f"    5. Запустить загрузку")
    print(f"    6. Аудит данных в bucket")
    print(f"    7. Сохранить и выйти")
    print(f"    0. Выйти без сохранения")
    print()
    val = input_line("  Выбор", "5")
    return val.strip()


def select_symbols(cfg, pairs):
    """Интерактивный выбор символов."""
    selected = set(cfg["symbols"])
    n = min(100, len(pairs))

    while True:
        print()
        print("  Выбор символов (топ по объёму):")
        print(f"  {' №':>4} {'Symbol':<14} {'Volume':>14}  {'Выбран':<6}")
        print(f"  {'────':>4} {'──────':<14} {'──────────':>14}  {'──────':<6}")

        for i, p in enumerate(pairs[:n], 1):
            vol = f"${p['volume_usd']/1e9:.1f}B" if p['volume_usd'] >= 1e9 else \
                  f"${p['volume_usd']/1e6:.1f}M" if p['volume_usd'] >= 1e6 else \
                  f"${p['volume_usd']:,.0f}"
            check = "[x]" if p["symbol"] in selected else "[ ]"
            print(f"  {i:>4} {p['symbol']:<14} {vol:>14}  {check:<6}")

        print()
        print(f"  Выбрано: {', '.join(sorted(selected)) if selected else '—'}")
        print(f"  Команды: 1 3 5-10, /BTC, top 20, all, clear, done")
        cmd = input_line("  >", "done")

        if cmd == "done" or cmd == "":
            cfg["symbols"] = sorted(selected) if selected else cfg["symbols"]
            return

        if cmd == "all":
            selected = {p["symbol"] for p in pairs}
        elif cmd == "clear":
            selected = set()
        elif cmd.startswith("top "):
            try:
                k = int(cmd.split()[1])
                selected = {p["symbol"] for p in pairs[:k]}
            except (IndexError, ValueError):
                print("  ❌ Неверный формат top N")
        elif cmd.startswith("/"):
            query = cmd[1:].upper()
            filtered = [(i, p) for i, p in enumerate(pairs[:n], 1) if query in p["symbol"]]
            if filtered:
                print(f"  Найдено {len(filtered)}:")
                for i, p in filtered:
                    check = "[x]" if p["symbol"] in selected else "[ ]"
                    print(f"    {i:>4} {p['symbol']} {check}")
                sub = input_line("  Номера для переключения (enter = назад)")
                if sub:
                    _toggle_numbers(sub, selected, pairs)
            else:
                print(f"  Ничего не найдено по '{query}'")
        else:
            _toggle_numbers(cmd, selected, pairs)


def _toggle_numbers(cmd, selected, pairs):
    """Обработать '1 3 5-10' — переключить выбор."""
    for part in cmd.split():
        if "-" in part:
            try:
                a, b = map(int, part.split("-"))
                for i in range(a, min(b + 1, len(pairs) + 1)):
                    sym = pairs[i - 1]["symbol"]
                    if sym in selected:
                        selected.remove(sym)
                    else:
                        selected.add(sym)
            except ValueError:
                pass
        else:
            try:
                i = int(part)
                if 1 <= i <= len(pairs):
                    sym = pairs[i - 1]["symbol"]
                    if sym in selected:
                        selected.remove(sym)
                    else:
                        selected.add(sym)
            except ValueError:
                pass


def select_types(cfg):
    """Переключение типов данных."""
    print()
    print("  Типы данных:")
    print(f"  ─{'─'*30}")
    for k, label in [("spot", "OHLCV спот"), ("perp", "OHLCV перп"),
                      ("funding", "Funding rate"), ("metrics", "Metrics (OI, L/S)")]:
        st = "да" if cfg["types"].get(k) else "нет"
        print(f"    {label:<22} {st}")
    print()
    val = input_line("  Переключить (spot/perp/funding/metrics/all/none)",
                     "enter = назад")
    if val.lower() in ("all", "все"):
        for k in cfg["types"]:
            cfg["types"][k] = True
    elif val.lower() in ("none", "нет"):
        for k in cfg["types"]:
            cfg["types"][k] = False
    elif val:
        for k in val.split():
            k = k.strip().lower()
            if k in cfg["types"]:
                cfg["types"][k] = not cfg["types"][k]


def select_years(cfg):
    """Выбор количества лет."""
    print()
    val = input_line("  Период (лет)", str(cfg["years"]))
    try:
        y = int(val)
        if y >= 1:
            cfg["years"] = min(y, 10)
    except ValueError:
        pass


def run_download(cfg):
    """Запустить загрузку с текущими настройками через download.py."""
    from data_fetcher.download import run_download as _run

    _run(
        symbols=cfg["symbols"],
        years=cfg["years"],
        types=cfg["types"],
        upload=cfg["upload"],
        tail=True,
    )


def _show_audit(cfg):
    """Запустить аудит по выбранным символам и типам."""
    from data_fetcher.audit import run_audit, print_report

    deduped = list(dict.fromkeys(cfg["symbols"]))
    active_types = [k for k, v in cfg["types"].items() if v]
    subdirs = {
        "spot": "ohlcv_spot", "perp": "ohlcv_perp",
        "funding": "funding", "metrics": "metrics",
    }
    dirs = [subdirs[t] for t in active_types if t in subdirs]

    if not dirs:
        print("\n  Нет выбранных типов данных для аудита")
        return

    print(f"\n  Аудит {len(deduped)} символов × {', '.join(active_types)}")
    print(f"  {'─'*60}")
    results = run_audit(dirs)

    # Фильтр: только файлы выбранных символов
    filtered = []
    for r in results:
        name = r["name"].split("/", 1)[1] if "/" in r["name"] else r["name"]
        s = name.split("_")[0]  # ETHUSDT_1h_2025 → ETHUSDT
        if s in deduped:
            filtered.append(r)

    if not filtered:
        print("\n  Нет данных в bucket для выбранных символов")
        return

    print_report(filtered)
    input("\n  Нажми Enter чтобы продолжить...")


def main():
    cfg = _load()
    pairs = None

    while True:
        action = show_menu(cfg)
        if action == "1":
            select_years(cfg)
        elif action == "2":
            if pairs is None:
                print("\n  Получение пар с Binance...")
                pairs = get_pairs()
                print(f"  Загружено: {len(pairs)} пар")
            select_symbols(cfg, pairs)
        elif action == "3":
            select_types(cfg)
        elif action == "4":
            cfg["upload"] = not cfg["upload"]
            print(f"\n  Upload: {'вкл' if cfg['upload'] else 'выкл'}")
        elif action == "5":
            _save(cfg)
            run_download(cfg)
            # после загрузки показать аудит
            print("\n  Проверка данных в bucket...")
            _show_audit(cfg)
            return
        elif action == "6":
            _show_audit(cfg)
        elif action == "7":
            _save(cfg)
            print("\n  Конфиг сохранён в menu_config.py")
            return
        elif action == "0":
            print("\n  Выход без сохранения.")
            return
        else:
            print("  ❌ Неверный выбор")


if __name__ == "__main__":
    main()
